# Generated by Django 4.2 on 2024-08-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True, verbose_name='Titulo')),
                ('descipcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='proyecto', verbose_name='Imagen')),
                ('link', models.URLField(blank=True, max_length=250, null=True, verbose_name='URL del proyecto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
